version: '3'
services:
  messenger:
    tty: true
    build:
      context: .
    environment:
      REDIS_URL: 'redis://redis:6379/1'
      ENC_KEY: ${ENC_KEY}
    volumes:
      - .:/challenge
    ports:
      - '3000:3000'

  redis:
    image: redis:7.4
    command: redis-server
    ports:
      - '6379:6379'