#!/bin/sh

bundle install --jobs 8
echo "****STARTING ENV****"
echo "****Checking Dev Cache****"

if ! test -f tmp/caching-dev.txt; then
  bash -lc "bundle exec rails dev:cache"
fi

echo "****Precompiling Assets****"
bash -lc "bundle exec rails assets:precompile"
echo "****Running Migrations****"
bash -lc "bundle exec rails db:migrate"
echo "**** ENV STARTED****"

# bash -c "rails s -b 0.0.0.0"

bash
